apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ .Values.fullName }}
spec:
  serviceName: {{ .Values.fullName }}
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullName}}
    spec:
      containers:
        - name: {{ .Values.containers.http_server.name}}
          image: {{ .Values.containers.http_server.image}}
          imagePullPolicy: {{ .Values.containers.http_server.pullPolicy}}
          ports:
            - containerPort:  {{ .Values.service.port}}
              name: http
              protocol: TCP
          volumeMounts:
            - name:  {{ .Values.storage.volumeName }}
              mountPath: /volume
          env:
            - name: baseDir
              value: "/volume/dist/modules/"
            - name: server.Host
              value: "0.0.0.0"
            - name: server.Port
              value:   "{{ .Values.service.port}}"
      terminationGracePeriodSeconds: 60
      volumes:
        - name: {{ .Values.storage.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.storage.volumeClimeName }}
  updateStrategy:
    type: RollingUpdate
