apiVersion: v1
kind: PersistentVolume
metadata:
  name:  {{ .Values.storage.volumeName }}
  labels:
      app: {{ .Values.selectorLabel }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 300Mi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem